# This is a basic workflow to help you get started with Actions

name: Pages Build

# Build for pushes to main or manual triggers
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/add-pages-build
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      - name: Install build target
        run: rustup target add wasm32-unknown-unknown
      - name: Install bindgen
        run: cargo install wasm-bindgen-cli

      - name: Build
        run: cargo build --release --target wasm32-unknown-unknown
      - name: push to release
        run: wasm-bindgen target/wasm32-unknown-unknown/release/hellorust.wasm --out-dir web --no-modules --no-typescript
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
          force_orphan: true
        #if: github.ref == 'refs/heads/master'
