name: Rust

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y libfontconfig-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
